**Pandas**

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr, index = labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

Data Frame

In [7]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2.columns = columns
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2[['Name','Salary',"City"]]

    Name  Salary      City
0   John   65000  New York
1   Anna   70000     Paris
2  Peter   62000    Berlin
3  Linda   85000    London

In [10]:
df2['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

Creating a new column

In [11]:
df2["Designation"] = ["Doctor", "Eng.","Doctor", "Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [12]:
df2[['Name', 'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [13]:
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2.drop(2,axis=0)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
3  Linda   42    London   85000        Eng.

In [15]:
df2.loc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation      Eng.
Name: 3, dtype: object

In [16]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [17]:
# I only want to see those people whose age is above 30

df2[df2['Age']>30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000        Eng.

In [18]:
# I only want to see those people whose age is above 30 and their city must be paris

df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.

**Missing Data**

In [19]:
import numpy as np
import pandas as pd

In [20]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [21]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Finding null values

In [22]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [23]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [24]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Droping a null value

In [25]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [26]:
# FIll null value with 0
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [27]:
values = {'A':0, 'B':100, "C":300, "D":400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [28]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**Merging Joining Concatination**

Merging

In [29]:
import pandas as pd
import numpy as np

In [30]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [31]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [32]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [33]:
pd.merge(employees, salaries, on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [34]:
pd.merge(employees, salaries, on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [35]:
pd.merge(employees, salaries, on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [36]:
pd.merge(employees, salaries, on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination

In [37]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [38]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [39]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [40]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [41]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining

In [42]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [43]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [44]:
df2

   score
2     85
3     90
4     75

In [45]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [46]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

Group by Aggregaion

In [47]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [48]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [49]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [50]:
df.groupby("A")["B"].sum()

A
1.0    1
2.0    2
4.0    4
5.0    5
Name: B, dtype: int64

In [51]:
import pandas as pd

data = {
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Employee": ["A", "B", "C", "D", "E"],
    "Salary": [50000, 60000, 40000, 45000, 55000]
}

df = pd.DataFrame(data)

print(df)

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   40000
3         HR        D   45000
4      Sales        E   55000

In [52]:
czt = df.groupby('Department')['Salary'].sum()
print(czt)

Department
HR        85000
IT       110000
Sales     55000
Name: Salary, dtype: int64

In [53]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [54]:

# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [55]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [56]:

# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [57]:
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [58]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

Pivot Tables

In [59]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    671     99   John  January      Q1
1  2023-01-02       B   West    337     43   Mary  January      Q1
2  2023-01-03       C  North    612     74    Bob  January      Q1
3  2023-01-04       D  South    874     71  Alice  January      Q1
4  2023-01-05       A   East    305     44   John  January      Q1
5  2023-01-06       B   West    851     75   Mary  January      Q1
6  2023-01-07       C  North    871     82    Bob  January      Q1
7  2023-01-08       D  South    196     31  Alice  January      Q1
8  2023-01-09       A   East    617     49   John  January      Q1
9  2023-01-10       B   West    299     76   Mary  January      Q1
10 2023-01-11       C  North    591     10    Bob  January      Q1
11 2023-01-12       D  South    143     18  Alice  January      Q1
12 2023-01-13       A   East    227     63   John  January      Q1
13 2023-01-14       B   West    923     58   Mary  January      Q1
14 2023-01-15       C  North    806     47    Bob  January      Q1
15 2023-01-16       D  South    789     26  Alice  January      Q1
16 2023-01-17       A   East    319     24   John  January      Q1
17 2023-01-18       B   West    123     32   Mary  January      Q1
18 2023-01-19       C  North    241     48    Bob  January      Q1
19 2023-01-20       D  South    894     70  Alice  January      Q1

In [60]:
pd.pivot_table(df,values = "Sales",index = 'Region', columns='Product')

Product      A      B      C      D
Region
East     427.8    NaN    NaN    NaN
North      NaN    NaN  624.2    NaN
South      NaN    NaN    NaN  579.2
West       NaN  506.6    NaN    NaN

In [61]:
pd.pivot_table(df,values = ["Sales","Units"],index = 'Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     427.8    NaN    NaN    NaN  55.8   NaN   NaN   NaN
North      NaN    NaN  624.2    NaN   NaN   NaN  52.2   NaN
South      NaN    NaN    NaN  579.2   NaN   NaN   NaN  43.2
West       NaN  506.6    NaN    NaN   NaN  56.8   NaN   NaN

Cross Tables

In [62]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**Operations**

In [63]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [64]:
df1.shape

(5, 3)

In [65]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [66]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [67]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [68]:
df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

Data Frames Applying Functions

In [69]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [70]:
def square(x):
  return x**2

In [71]:
df1['B'] = df1['B'].apply(square)

In [72]:
df1['B'] = df1['B'].apply(lambda x: x**2)

Feature Extrsaction

In [73]:
# Loading the data
df = pd.read_csv("anime.csv")

In [ ]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [74]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [75]:
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [ ]:
def extract_ep(txt):
  check = False
  data = ""
  for i in txt :
    if i == ")":
      check = False
      return data
    if check == True :
      data = data + i
    if i == "(" :
      check = True

In [ ]:

df["Title"].apply(extract_ep)

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: object

In [ ]:
df["Episods"]= df["Title"].apply(extract_ep)

In [ ]:
df

In [ ]:
df["Episods"] = df["Episods"].str.replace("eps","")

In [ ]:
df["Episods"]=df["Episods"].astype(int)

In [ ]:
df

In [ ]:
df.loc[0]["Title"]

In [ ]:
def extractiom_time(txt):
  check = False
  data = ""
  for i in range(len(txt)) :
    if txt[i] == ')' :
      for j in range(i+1, i+20):
        data += txt[j]
      return data

In [ ]:
df["Total Time"] = df["Title"].apply(extractiom_time)

In [ ]:
df.head()

In [ ]:
df[df['Score'] == df['Score'].max()]["Title"]

In [ ]:
df['Episods']==df["Episods"].max()